### ISSUE TITLE
请问您测试过最高能够达到多少pps呢?

### ISSUE THREAD

**Issue by Multhree** [alandtsang/mydpdkdns#1]

**Comment by alandtsang** [comment]
示例中是在我虚拟机中的测试数据。
在实际 Intel 10g 单网卡环境中，在不开启日志和地址库解析的情况下，只做 UDP DNS 解析并返回，能达到 980w pps。
开启日志和地址库解析的情况下，能达到 260w pps。

**Comment by Multhree** [comment]
感谢您的回复！
再请教一下，DNS查询是用pktgen高速发包的吗？四个thread都分别绑定一个lcore吗？

**Comment by alandtsang** [comment]
是的，pktgen + lua 进行的发包。
对，是分别绑核的。
