### ISSUE TITLE
编译程序报错，错误内容如下，请问是什么问题

### ISSUE THREAD

**Issue by houfengjiejie** [alandtsang/mydpdkdns#2]
root@9.25.15.89:/data/hfj/mydpdkdns-master/tools# ./start.sh 
/data/hfj/mydpdkdns-master
-- RTE_SDK path：/data/hfj/dpdk-src
-- RTE_TARGET path：
-- RTE_SDK include path：/data/hfj/dpdk-src/include
-- RTE_SDK library path：/data/hfj/dpdk-src/lib
-- Configuring done
-- Generating done
-- Build files have been written to: /data/hfj/mydpdkdns-master/build
[ 16%] Building CXX object CMakeFiles/dserver.dir/src/logger.cpp.o
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:40:1: fatal error: /data/hfj/dpdk-src//include/rte_config.h: No such file or directory
 #endif
 ^
compilation terminated.
make[2]: *** [CMakeFiles/dserver.dir/src/logger.cpp.o] Error 1
make[1]: *** [CMakeFiles/dserver.dir/all] Error 2
make: *** [all] Error 2
root@9.25.15.89:/data/hfj/mydpdkdns-master/tools# ./start.sh: line 28: ./bin/dserver: No such file or directory

**Comment by alandtsang** [comment]
看着是找不到 dpdk 的 rte_config.h 文件，有执行下面命令么？
```
make config T=x86_64-native-linuxapp-gcc
make
make install T=x86_64-native-linuxapp-gcc
```
